
### Register
POST http://localhost:5031/api/Auth/Register
Content-Type: application/json

{
  "fullName": "fuck off",
  "email": "dan@example.com",
  "password": "StrongPass#123",
  "confirmPassword": "StrongPass#123"
}

### Login
POST http://localhost:5031/api/Auth/Login
Content-Type: application/json

{
  "email": "dan@example.com",
  "password": "StrongPass#123"
}


